ALTER TABLE `t_tlnt_rsum`
ADD COLUMN `SYS_REF_TLNT`  varchar(9) NULL AFTER `SYS_REF_RSUM`;

ALTER TABLE `t_tlnt_rsum` ADD CONSTRAINT `T_TLNT_RSUM_TLNT_FK` FOREIGN KEY (`SYS_REF_TLNT`) REFERENCES `t_tlnt_bs_inf` (`SYS_REF_TLNT`) ON DELETE RESTRICT ON UPDATE RESTRICT;

