DROP TABLE IF EXISTS T_TLNT_SLF_EVLUTN;
DROP TABLE IF EXISTS T_TLNT_JB_INT;

##人才自我评价
CREATE TABLE T_TLNT_SLF_EVLUTN (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '简历编号',
  CNT varchar(1000) COMMENT '内容',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM),
  CONSTRAINT T_SLF_EVLUTN_RSUM_FK FOREIGN KEY (SYS_REF_RSUM) REFERENCES T_TLNT_RSUM(SYS_REF_RSUM)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

##人才求职意向
CREATE TABLE T_TLNT_JB_INT (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '简历编号',
  JB_TY varchar(2) NOT NULL COMMENT '期望工作性质(FT-全职/PT-兼职/IS-实习)',
  EXP_ADDR varchar(50) NOT NULL COMMENT '期望工作地点',
  EXP_POST varchar(3) NOT NULL COMMENT '期望职业',
  EXP_IND varchar(3) NOT NULL COMMENT '期望行业',
  EXP_SALRY varchar(10) NOT NULL COMMENT '期望月薪',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM),
  CONSTRAINT T_JB_INT_RSUM_FK FOREIGN KEY (SYS_REF_RSUM) REFERENCES T_TLNT_RSUM(SYS_REF_RSUM)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;