ALTER TABLE t_cust_co
MODIFY COLUMN GP_FLAG  varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否集团客户' AFTER CO_SZ;

ALTER TABLE t_prj
ADD COLUMN PRJ_ST  varchar(3) NULL COMMENT '项目状态' AFTER LST_TX_ACTN,
ADD COLUMN PRJ_ADVSR  varchar(10) NULL COMMENT '项目负责人' AFTER PRJ_ST;
