DROP TABLE IF EXISTS T_UPLD_CV;

##附件简历表
CREATE TABLE T_UPLD_CV (
  SYS_REF_CV varchar(9) NOT NULL COMMENT '简历编号(YYMMDD+3位SEQUENCE)',
  SYS_REF_TLNT varchar(9) NOT NULL COMMENT '人才编号',
  CV_NM varchar(50) NOT NULL COMMENT '简历名称',
  CV_LAN varchar(2) NOT NULL COMMENT '简历语言',
  UPLD_LCTN varchar(200) COMMENT '简历上传相对路径',
  SWF_LCTN varchar(200) COMMENT 'SWF相对路径',
  ATCH_SZ varchar(10) COMMENT '文件大小',
  ENCRY_FLG varchar(1) COMMENT '是否已加密',
  CONVT_FLG varchar(1) COMMENT '是否已转换',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_CV),
  CONSTRAINT T_ATCH_UPLD_CV_FK_TLNT FOREIGN KEY (SYS_REF_TLNT) REFERENCES T_TLNT_BS_INF(SYS_REF_TLNT)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO T_SEQ_NBR_LST
VALUES ('SEQ_UPLD_CV' , 1 ,'上传简历ID' , '2012072401', '2012-07-25', '2012072401', '2012-07-25', 'I');