CREATE USER 'EHT_INT_APPL'@'localhost' IDENTIFIED BY 'jELUQNBO+zjpva2naZuJRQ==';##cabordersapplication
CREATE USER 'EHT_OUT_APPL'@'localhost' IDENTIFIED BY 'fmz/NeFyO+xOMJXud9uBbA==';##caborders

GRANT SELECT, INSERT , UPDATE , DELETE , REFERENCES , INDEX ON ehunter.* TO 'EHT_INT_APPL'@'localhost';
GRANT SELECT, REFERENCES , INDEX ON ehunter.T_INFO_CENTR TO 'EHT_OUT_APPL'@'localhost';
GRANT SELECT, REFERENCES , INDEX ON ehunter.T_RLESD_POSTN TO 'EHT_OUT_APPL'@'localhost';
GRANT SELECT, REFERENCES , INDEX ON ehunter.T_PRVC TO 'EHT_OUT_APPL'@'localhost';
GRANT SELECT, REFERENCES , INDEX ON ehunter.T_CITY TO 'EHT_OUT_APPL'@'localhost';

GRANT SELECT, INSERT , UPDATE , DELETE , REFERENCES , INDEX ON ehunter_uat.* TO 'EHT_APPL'@'localhost';
FLUSH PRIVILEGES;


