ALTER TABLE T_TLNT_JB_INT
MODIFY COLUMN EXP_ADDR  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '期望工作地点' AFTER JB_TY,
MODIFY COLUMN EXP_POST  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '期望职业' AFTER EXP_ADDR,
MODIFY COLUMN EXP_IND  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '期望行业' AFTER EXP_POST;