ALTER TABLE T_TLNT_CERT DROP FOREIGN KEY T_CERT_FK_TLNT;
ALTER TABLE T_TLNT_EDU_EXP DROP FOREIGN KEY T_EDU_EXP_FK_TLNT;
ALTER TABLE T_TLNT_JOB_EXP DROP FOREIGN KEY T_JOB_EXP_FK_TLNT;
ALTER TABLE T_TLNT_LAN_ABLT DROP FOREIGN KEY T_LAN_ABLT_FK_TLNT;
ALTER TABLE T_TLNT_PRJ_EXP DROP FOREIGN KEY T_PRJ_EXP_FK_TLNT;
ALTER TABLE T_TLNT_PRO_SKL DROP FOREIGN KEY T_RPO_TECH_FK_TLNT;
ALTER TABLE T_TLNT_TRN_EXP DROP FOREIGN KEY T_TRN_EXP_FK_TLNT;

DROP TABLE IF EXISTS T_TLNT_RSUM;

##人才簡歷
CREATE TABLE T_TLNT_RSUM (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '人才简历编号(R+人才编号+3位序列号)',
  RSUM_NM varchar(50) NOT NULL UNIQUE COMMENT '简历名称',
  RSUM_LAN varchar(2) NOT NULL UNIQUE COMMENT '简历语言版本',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS T_TLNT_EDU_EXP;
DROP TABLE IF EXISTS T_TLNT_JOB_EXP;
DROP TABLE IF EXISTS T_TLNT_TRN_EXP;
DROP TABLE IF EXISTS T_TLNT_LAN_ABLT;
DROP TABLE IF EXISTS T_TLNT_PRO_SKL;
DROP TABLE IF EXISTS T_TLNT_PRJ_EXP;
DROP TABLE IF EXISTS T_TLNT_CERT;

##人才教育经历
CREATE TABLE T_TLNT_EDU_EXP (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '简历编号',
  EXP_SEQ_NBR int(2) NOT NULL COMMENT '经历序号',
  BEGN_DTTM date NOT NULL COMMENT '开始时间',
  GRDUAT_DTTM date COMMENT '毕业时间',
  SCHOOL varchar(50) COMMENT '学校',
  MAJOR varchar(50) COMMENT '专业',
  DEGREE varchar(3) COMMENT '学位',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM,EXP_SEQ_NBR),
  CONSTRAINT T_EDU_EXP_FK_RSUM FOREIGN KEY (SYS_REF_RSUM) REFERENCES T_TLNT_RSUM(SYS_REF_RSUM)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

##人才工作经历
CREATE TABLE T_TLNT_JOB_EXP (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '简历编号',
  EXP_SEQ_NBR int(2) NOT NULL COMMENT '经历序号',
  BEGN_DTTM date NOT NULL COMMENT '开始时间',
  LEV_DTTM date COMMENT '离职时间',
  CO_NM varchar(50) COMMENT '公司名称',
  CO_TY varchar(2) COMMENT '企业性质',
  CO_SCOP varchar(3) COMMENT '企业规模',
  IND_TY varchar(3) COMMENT '行业类别',
  DEPT_NM varchar(50) COMMENT '部门名称',
  POST_TY varchar(3) COMMENT '职位类别',
  POST_NM varchar(50) COMMENT '职位名称',
  PRE_TAX_SALARY int COMMENT '税前月薪',
  POST_DESC varchar(300) COMMENT '职位描述',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM,EXP_SEQ_NBR),
  CONSTRAINT T_JOB_EXP_FK_RSUM FOREIGN KEY (SYS_REF_RSUM) REFERENCES T_TLNT_RSUM(SYS_REF_RSUM)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

##人才培训经历
CREATE TABLE T_TLNT_TRN_EXP (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '简历编号',
  EXP_SEQ_NBR int(2) NOT NULL COMMENT '经历序号',
  BEGN_DTTM date NOT NULL COMMENT '开始时间',
  END_DTTM date COMMENT '结束时间',
  TRN_ORG varchar(50) NOT NULL COMMENT '培训机构',
  TRN_ADDR varchar(300) COMMENT '培训地点',
  TRN_COUS varchar(50) COMMENT '培训课程',
  GAIN_CERT varchar(50) COMMENT '获得证书',
  TRN_DESC varchar(100) COMMENT '培训描述',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM,EXP_SEQ_NBR),
  CONSTRAINT T_TRN_EXP_FK_RSUM FOREIGN KEY (SYS_REF_RSUM) REFERENCES T_TLNT_RSUM(SYS_REF_RSUM)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

##人才语言能力
CREATE TABLE T_TLNT_LAN_ABLT (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '简历编号',
  ABLT_SEQ_NBR int(2) NOT NULL COMMENT '语言能力序号',
  LAN_TY varchar(3) NOT NULL COMMENT '语言类型',
  RW_ABLT varchar(3) COMMENT '读写能力',
  LS_ABLT varchar(3) COMMENT '听说能力',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM,ABLT_SEQ_NBR),
  CONSTRAINT T_LAN_ABLT_FK_RSUM FOREIGN KEY (SYS_REF_RSUM) REFERENCES T_TLNT_RSUM(SYS_REF_RSUM)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

##人才专业技能
CREATE TABLE T_TLNT_PRO_SKL (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '简历编号',
  SKL_SEQ_NBR int(2) NOT NULL COMMENT '技能序号',
  SKL_TY varchar(3) COMMENT '技能类型',
  USE_DURTN int(2) COMMENT '使用时间',
  CNTL_LEVL varchar(3) COMMENT '掌握程度',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM,SKL_SEQ_NBR),
  CONSTRAINT T_RPO_TECH_FK_RSUM FOREIGN KEY (SYS_REF_RSUM) REFERENCES T_TLNT_RSUM(SYS_REF_RSUM)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

##人才项目经验
CREATE TABLE T_TLNT_PRJ_EXP (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '简历编号',
  EXP_SEQ_NBR int(2) NOT NULL COMMENT '经验序号',
  BEG_DTTM date NOT NULL COMMENT '开始时间',
  END_DTTM date COMMENT '结束时间',
  PRJ_NM varchar(50) COMMENT '项目名称',
  PRJ_DUTY varchar(50) COMMENT '项目职责',
  PRJ_DESC varchar(300) COMMENT '项目描述',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM,EXP_SEQ_NBR),
  CONSTRAINT T_PRJ_EXP_FK_RSUM FOREIGN KEY (SYS_REF_RSUM) REFERENCES T_TLNT_RSUM(SYS_REF_RSUM)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

##人才证书
CREATE TABLE T_TLNT_CERT (
  SYS_REF_RSUM varchar(12) NOT NULL COMMENT '简历编号',
  CERT_SEQ_NBR int(2) NOT NULL COMMENT '证书序号',
  CERT_NM varchar(50) COMMENT '证书名称',
  GAIN_DTTM date COMMENT '获得时间',
  SCORE varchar(4) COMMENT '分数',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_RSUM,CERT_SEQ_NBR),
  CONSTRAINT T_CERT_FK_RSUM FOREIGN KEY (SYS_REF_RSUM) REFERENCES T_TLNT_RSUM(SYS_REF_RSUM)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;