ALTER TABLE `t_tlnt_prj_exp`
MODIFY COLUMN `PRJ_DUTY`  varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '项目职责' AFTER `PRJ_NM`,
MODIFY COLUMN `PRJ_DESC`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '项目描述' AFTER `PRJ_DUTY`;

