DROP TABLE IF EXISTS T_PRJ_POST_SALRY_CMPS;
DROP TABLE IF EXISTS T_PRJ_POST_SCTY_WELF;
DROP TABLE IF EXISTS T_PRJ_POST_ANUL_WELF;
DROP TABLE IF EXISTS T_PRJ_POST_LAN_REQ;
DROP TABLE IF EXISTS T_PRJ_POST_KEY_WD;
DROP TABLE IF EXISTS T_PRJ_POST_DESC;
DROP TABLE IF EXISTS T_PRJ_POST_REQ;

##项目职位描述
CREATE TABLE T_PRJ_POST_DESC (
  SYS_REF_POST varchar(9) NOT NULL COMMENT '项目职位编号',
  POST_NM varchar(30) NOT NULL COMMENT '职位名称',
  POST_TY varchar(3) NOT NULL COMMENT '职位分类',
  POST_DEPT varchar(50) COMMENT '所属部门',
  PEPT_TO varchar(50) COMMENT '汇报对象',
  UDLNG_NBR int COMMENT '下属人数',
  WK_CTS varchar(30) COMMENT '工作地点',
  EXPR_DT date COMMENT '截至日期',
  YRLY_SALRY_FR int COMMENT '职位年薪from',
  YRLY_SALRY_TO int COMMENT '职位年薪to',
  SALRY_CMPS varchar(20) COMMENT '薪资构成',
  SCTY_WELF varchar(20) COMMENT '社会福利',
  RSDTL_WELF varchar(20) COMMENT '居住福利',
  ANUL_LVE_WELF varchar(20) COMMENT '年假福利',
  DUTY_DESC varchar(4000) NOT NULL COMMENT '职责描述',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_POST),
  CONSTRAINT T_PRJ_POST_DESC_FK_PRJ FOREIGN KEY (SYS_REF_POST) REFERENCES T_PRJ(SYS_REF_PRJ)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

##项目职位要求
CREATE TABLE T_PRJ_POST_REQ (
  SYS_REF_POST varchar(9) NOT NULL COMMENT '项目职位编号',
  AG_FR int COMMENT '年龄要求from',
  AG_TO int COMMENT '年龄要求to',
  GNDR_REQ varchar(1) COMMENT '性别要求',
  SUBJ_REQ varchar(3) COMMENT '专业要求',
  JOB_EXP_REQ int COMMENT '工作年限要求',
  EDU_REQ varchar(3) COMMENT '学历要求',
  FL_TM_EDU_FLG varchar(1) COMMENT '是否全日制统招',
  LAN_REQ varchar(30) COMMENT '语言要求',
  OFER_REQ_DESC varchar(4000) COMMENT '任职资格说明',
  EXPT_INDS varchar(20) COMMENT '期望行业',
  REMK varchar(300) COMMENT '补充说明',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_POST),
  CONSTRAINT T_PRJ_POST_REQ_FK_PRJ FOREIGN KEY (SYS_REF_POST) REFERENCES T_PRJ(SYS_REF_PRJ)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

##职位关键词
CREATE TABLE T_PRJ_POST_KEY_WD (
  SYS_REF_POST varchar(9) NOT NULL COMMENT '项目职位编号',
  SEQ_NBR int NOT NULL COMMENT '关键词序号',
  KEY_WD_CNT varchar(20) NOT NULL COMMENT '关键词内容',
  CR_BY varchar(10) COMMENT '创建人',
  CR_DTTM date COMMENT '创建时间',
  LST_UPD_BY varchar(10) COMMENT '最近更新人',
  LST_UPD_DTTM date COMMENT '最近更新时间',
  LST_TX_ACTN varchar(1) COMMENT '最近执行操作',
  PRIMARY KEY (SYS_REF_POST,SEQ_NBR),
  CONSTRAINT T_PRJ_POST_KEY_WD_FK_POST FOREIGN KEY (SYS_REF_POST) REFERENCES T_PRJ_POST_DESC(SYS_REF_POST)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;